import json
from datetime import datetime, timedelta
from typing import List, Dict, Optional, Any

# Assuming these files were generated by agents/dataset.py in the previous step
CUSTOMERS_FILE = "data/customers.json"
EVENTS_FILE = "data/sample_data.json"
OUTPUT_FILE = "data/flagged_events.json"
NOW = datetime.now()

def load_data():
    with open(CUSTOMERS_FILE, 'r') as f:
        customers = json.load(f)
    with open(EVENTS_FILE, 'r') as f:
        events = json.load(f)
    
    # Index customers for quick lookup
    customer_map = {c['customer_id']: c for c in customers}
    return customer_map, events

def calculate_priority_score(event: Dict[str, Any], customer: Optional[Dict[str, Any]], amount: float, urgency_decay_hours: int) -> float:
    """Calculates priority score 0-100."""
    score = 0
    
    # 1. Amount component (Max 40 points)
    # Scale based on arbitrary range 0-50,000
    score += min(40, (amount / 50000) * 40)
    
    # 2. Urgency component (Max 40 points)
    timestamp_str = event.get('timestamp')
    if timestamp_str:
        try:
            timestamp = datetime.fromisoformat(timestamp_str)
            time_diff = (NOW - timestamp).total_seconds() / 3600
            if time_diff < urgency_decay_hours:
                # Closer to decay = higher score
                urgency_ratio = 1 - (time_diff / urgency_decay_hours)
                score += (urgency_ratio * 40)
        except Exception:
            pass # Null or malformed timestamps handled by caller or elsewhere
    
    # 3. Risk component (Max 20 points)
    if customer:
        risk_map = {"low": 5, "medium": 10, "high": 20}
        score += risk_map.get(customer.get('risk_profile', 'low'), 5)
        
    return min(100, round(score, 2))

def run_detection():
    customer_map, events = load_data()
    
    flagged_events = []
    summary = {
        "total_scanned": 0,
        "total_flagged": 0,
        "total_skipped": 0,
        "total_warnings": 0,
        "breakdown": {}
    }
    
    for event in events:
        summary["total_scanned"] += 1
        warnings = []
        event_id = event.get('event_id')
        
        # Check for duplicate IDs
        if any(f['event_id'] == event_id for f in flagged_events):
            warnings.append(f"Duplicate event_id: {event_id}")
            summary["total_warnings"] += 1
            
        customer_id = event.get('customer_id')
        customer = customer_map.get(customer_id)
        
        if not customer and customer_id != "CUST-9999": # Handle orphan check
            # For this scenario, just log warning if customer is missing
            warnings.append(f"Orphan customer_id: {customer_id}")
            summary["total_warnings"] += 1
        elif customer_id == "CUST-9999":
            warnings.append("Orphan customer_id detected: CUST-9999")
            summary["total_warnings"] += 1
            
        event_type = event.get('event_type')
        amount = event.get('amount', event.get('cart_value', event.get('mrr_amount', event.get('invoice_amount', 0))))
        
        # Rule-based flagging
        is_at_risk = False
        reason = None
        
        # Edge case: Zero amount
        if amount == 0:
            summary["total_skipped"] += 1
            continue

        # Edge case: Null timestamp
        if not event.get('timestamp'):
            warnings.append("Null timestamp detected")
            summary["total_warnings"] += 1
            
        if event_type == 'failed_payment':
            is_at_risk = True
            reason = "Always at risk unless resolved"
        elif event_type == 'checkout_abandoned':
            timestamp = datetime.fromisoformat(event.get('timestamp')) if event.get('timestamp') else None
            if timestamp and (NOW - timestamp).total_seconds() / 3600 < 24:
                is_at_risk = True
                reason = "Within 24h urgency window"
        elif event_type == 'subscription_failed':
            # Cap 3 retries
            if event.get('retry_count', 0) < 3:
                is_at_risk = True
                reason = "Retry count below cap"
        elif event_type == 'overdue_receivable':
            is_at_risk = True
            reason = "Overdue"
        else:
            # Handle unknown event types
            warnings.append(f"Unknown event type: {event_type}")
            summary["total_warnings"] += 1
            
        if is_at_risk:
            summary["total_flagged"] += 1
            summary["breakdown"][event_type] = summary["breakdown"].get(event_type, 0) + 1
            
            flagged_event = {
                "event_id": event_id,
                "event_type": event_type,
                "customer_id": customer_id,
                "amount": amount,
                "priority_score": calculate_priority_score(event, customer, amount, event.get('urgency_decay_hours', 24)),
                "contact_opt_out": customer.get('contact_opt_out', False) if customer else False,
                "flag_reason": reason,
                "warnings": warnings
            }
            flagged_events.append(flagged_event)

    # Save to file
    with open(OUTPUT_FILE, 'w') as f:
        json.dump(flagged_events, f, indent=2)
        
    # Print Summary
    print("--- DETECTION AGENT SUMMARY ---")
    print(f"Total events scanned: {summary['total_scanned']}")
    print(f"Total flagged: {summary['total_flagged']}")
    print(f"Total skipped: {summary['total_skipped']}")
    print(f"Total warnings: {summary['total_warnings']}")
    print("Breakdown by event_type:")
    for et, count in summary["breakdown"].items():
        print(f"  {et}: {count}")

if __name__ == "__main__":
    run_detection()
